### ISSUE TITLE
[Suggestion] Anti Friendly Fire and Anti Spam

### ISSUE THREAD

**Issue by Woogoo336** [chuxiaaaa/AntiCheat#10]
A toggleable feature to prevent players from damaging each other would be very nice to have in public lobbies. Much of the cheat stuff is blocked with this mod which is really great, but that only leaves friendly fire left. Also, I have encountered a new way to spam where a player enters emojis into the text chat which block most of the screen. It is also impossible to see who is sending them.

**Comment by chuxiaaaa** [comment]
I believe friendly fire is part of the game's content, and for the spamming issue, I will introduce a configuration to limit the text length to address it.

**Comment by chuxiaaaa** [comment]
After conducting a test on the issue of spam messages, it appears that players are unable to send a large volume of messages. It's possible that the spam issue may be caused by a mod on your local setup?

**Comment by Woogoo336** [comment]
It isn't long messages but single emojis like a smiley face. Imagine a single one of these taking up the entire screen "😂". I'm not sure how it's done, possibly a copy paste Lethal isn't processing correctly?
