### ISSUE TITLE
[英语本土化] 我会尝试着帮你把一些英语部分修正一下

### ISSUE THREAD

**Issue by CoolLKKPS** [chuxiaaaa/AntiCheat#11]
我注意到一些部分的英语本土内容有问题，我会稍微帮你修改一下，这样或许能吸引真正原生英语口语者来帮助翻译内容，你看可以吗？

**Comment by chuxiaaaa** [comment]
Of course, you can make the necessary changes and submit a Pull request.

**Comment by CoolLKKPS** [comment]
https://github.com/chuxiaaaa/AntiCheat/pull/12

**Comment by CoolLKKPS** [comment]
@chuxiaaaa 有一个问题，这个选项我得完全明白

**Comment by chuxiaaaa** [comment]
哪个？

**Comment by CoolLKKPS** [comment]
> Non-homeowners can only take off when the number of people in the spaceship (survival) exceeds the above ratio (0-100%)
这个选项是非主机的情况下可以起飞，如果在船上的存活人数大于这个百分比，那么这个百分比指的是总人数还是总存活人数？

**Comment by chuxiaaaa** [comment]
存活百分比，例如，设定50%，10个人的房间，死了4个，还活着6个，50%就是有3个需要在飞船里面，否则无法拉杆

**Comment by CoolLKKPS** [comment]
ok，我忘记我标记了一个注释在那里，那时候忘记问你了，现在应该没问题了
https://github.com/chuxiaaaa/AntiCheat/pull/13
