### ISSUE TITLE
[Issue] Trigger Infinite Ammo false report from client-side user

### ISSUE THREAD

**Issue by CoolLKKPS** [chuxiaaaa/AntiCheat#14]
我注意到一个问题，这个问题在【前天】发生，这可能导致了不少误BAN事实上（对我而言并没有）
无限子弹检测问题：在客机拿起并尝试射击时，可能是因为霰弹枪子弹为空的问题，他应该是反复按左键开枪（虽然我觉得他这种行为我很不认可，他枪是对着人的，或者说是对着我的，也提醒过他放下枪很多遍）
他先后拿起两三把枪，全是空子弹的，因为我事先清空了子弹只留了一个上满子弹的霰弹枪藏在角落，但他即使射击的是完全没子弹的霰弹枪也能触发无限子弹检测，而且在这之后我最信任的朋友也拿起那个空枪开枪，也触发了提示
由于我开的是英语，我朋友并没注意到这个提示，那时候我们就很正常的继续游戏，但不知道为什么我忘记当天记下反馈了
 \- 我会继续跟踪这个问题，以便能够追查到其实际原因

**Comment by chuxiaaaa** [comment]
确实有误判的可能，原因大概率是有人开了无限子弹让其他客户端也认为这把枪有子弹

**Comment by CoolLKKPS** [comment]
十分有可能，但不太好说，我打算先单独找个人测试正常情况，我会先把这个问题暂时搁置，但我偏向你的说法事实上

**Comment by CoolLKKPS** [comment]
确认，普通情况是绝对不会触发无限子弹检测，只有有作弊者的情况才会有
