### ISSUE TITLE
Retranslation

### ISSUE THREAD

**Issue by glyphical** [chuxiaaaa/AntiCheat#22]
Hi, I have no idea how GitHub works and Chuxiaaaa's discord was not available  anymore, so this is the only way I know I can offer this. 

I have retranslated the mod's messages into perfect, fluent English, inside the code file and ready to be updated. This mod is one of my favorites and has absolutely improved the multiplayer experience, so I would like to help.

**Comment by chuxiaaaa** [comment]
You can try to do a Google search for GitHub pull request tutorials, or if you don't know how to do it, you can submit an attachment to this issue and I'll credit you with the contribution

**Comment by glyphical** [comment]
[translation .txt](https://github.com/chuxiaaaa/AntiCheat/files/14761258/translation.txt) The attachment would likely be much quicker, so here it is. Thank you for the wonderful mod!

**Comment by glyphical** [comment]
Apologies, use this  one: 
[translation .txt](https://github.com/chuxiaaaa/AntiCheat/files/14761313/translation.txt)
it contains 2 fixed typos and should be completely solid now.

**Comment by glyphical** [comment]
Sorry, one more. I decided to go ahead and retranslate the config messages too, so everything should be a bit clearer now.

[translation .txt](https://github.com/chuxiaaaa/AntiCheat/files/14761492/translation.txt)

This should now be ready to go.

**Comment by glyphical** [comment]
[translation .txt](https://github.com/chuxiaaaa/AntiCheat/files/14761523/translation.txt)
... except I missed one last typo. Okay, for real, this is the last one. Thanks!

**Comment by chuxiaaaa** [comment]
Your submission will be merged by @CoolLKKPS  in #20

**Comment by glyphical** [comment]
Fantastic to hear, glad to help. Have a good day Chuxiaaaa!

**Comment by CoolLKKPS** [comment]
@glyphical hey, just let u know u can send a PR (Pull Request) in my fork repository, and when u ready u can just mention me in the PR comment, will respond as soon as i received the email: https://github.com/CoolLKKPS/AntiCheat
and thx for ur english translation!

**Comment by glyphical** [comment]
@CoolLKKPS Unfortunately I'm a little too inexperienced with GitHub to really understand how pull requests work or to competently submit one. I'm not too worried about being credited, I simply wished to help! My GitHub account doesn't have anything on it anyway, so there's not much to credit. :P

**Comment by glyphical** [comment]
If you do need it though, I can try to figure out how to do it, or if there's some other way I could help, let me know!

**Comment by chuxiaaaa** [comment]
Any other questions? Can we close this issue now?

**Comment by glyphical** [comment]
Yes, go ahead.
