### ISSUE TITLE
[Conflict] cosmetics will blocked by anti-cheat mod

### ISSUE THREAD

**Issue by CoolLKKPS** [chuxiaaaa/AntiCheat#25]
https://github.com/notnotnotswipez/MoreCompany/issues/73

**Comment by CoolLKKPS** [comment]
@chuxiaaaa

**Comment by 1A3Dev** [comment]
Just to save some time debugging it's probably due to this `return false` https://github.com/chuxiaaaa/AntiCheat/blob/main/AntiCheat/Patch.cs#L1650

**Comment by chuxiaaaa** [comment]
This issue has been addressed, please update to version 0.6.4 for testing

**Comment by CoolLKKPS** [comment]
ok, should be fixed
