### ISSUE TITLE
Mod is no longer host only?

### ISSUE THREAD

**Issue by glyphical** [chuxiaaaa/AntiCheat#28]
I am currently having issues where I believe the AC mod no longer works in public lobbies. If I host a public lobby with this mod, no one will join no matter how long I wait, and people join instantly without it. It is likely no longer compatible with clients who don't have the mod and needs an update.

**Comment by chuxiaaaa** [comment]
Anti Cheat has not changed any code recently, it may be a compatibility issue caused by your other mods

**Comment by chuxiaaaa** [comment]
OK, I found the problem, it may be some problems caused by zeekeers update, but now the new version has solved it
