### ISSUE TITLE
Cannot use text chat on AC lobbies.

### ISSUE THREAD

**Issue by rando-idiot** [chuxiaaaa/AntiCheat#29]
Well, this is a sort of lie. I can USE text chat, but nobody can read the contents of my messages.

**Comment by chuxiaaaa** [comment]
No one else has reported this problem to me. It is probably a module conflict or something like that. When you encounter this problem, are you a client or a server?

**Comment by rando-idiot** [comment]
> No one else has reported this problem to me. It is probably a mod conflict or something like that. When you encounter this problem, are you a client or a server?

also its probably because you have no other reported issues
ive ran this on vanilla in AC lobbies

**Comment by chuxiaaaa** [comment]
After testing, everything is OK. Please check your other mods. If you think it is the anti-cheat that is causing the problem, please provide pictures or videos to let me know what happened (logs are also required)

**Comment by rando-idiot** [comment]
nevermind for some reason it works now
to be perfectly frank i have no idea what the fuck was happening
