### ISSUE TITLE
Jetpack holders can't pick up two-handed items

### ISSUE THREAD

**Issue by Nicnl** [chuxiaaaa/AntiCheat#30]
I've noticed this issue multiple times.   
Anytime a client player has a jetpack in their inventory, they can't pick up some items.   
I think it only happens with two-handed items, because standard items have no issues I think.

**Comment by chuxiaaaa** [comment]
To prevent players from using a jetpack to fly after picking up a two-handed item, two-handed items cannot be picked up while wearing a jetpack

**Comment by Nicnl** [comment]
Is there a way to disable this?   
Such a feature feels too restrictive because it interferes with normal gameplay

**Comment by chuxiaaaa** [comment]
Disable picking up items detection

**Comment by Nicnl** [comment]
Oh ok it's this one    
Sorry for bothering you, I should have searched better

Thank you for your great work   
have a nice day!
