### ISSUE TITLE
Framerate issues 0.4.6/0.4.7

### ISSUE THREAD

**Issue by DeathWrench** [chuxiaaaa/AntiCheat#8]
0.4.5 does not seem to have this issue, but getting lots of FPS drops on the newer version.

**Comment by Woogoo336** [comment]
I'm seeing this as well. No other mods installed.

**Comment by chuxiaaaa** [comment]
Sorry, I will resolve it as soon as possible

**Comment by chuxiaaaa** [comment]
Version 0.4.8 may have addressed the issue, at least the FPS is no longer low. If there are still any problems, please continue to reply.

**Comment by DeathWrench** [comment]
Seems to have fixed it.
